#!/bin/bash
#
# https://stackoverflow.com/questions/34890313/deleting-all-git-cached-submodules-from-repository
if [ 1 -eq 1 ]; then
  echo 'deinit all submodules from .gitmodules...'
  git submodule deinit .
  echo 'remove all submodules (`git rm`) from .gitmodules...'
  #git submodule | cut -c43- | while read -r line; do (git rm -f "$line"); done
  git submodule | awk '{print $2}' | while read -r line; do (git rm -f "$line"); done
fi
echo 'add all submodules...'
for I in {1..16}; do
  DIR=""
  URL=""
  BRANCH="master"
  case $I in
  1)
  DIR=external/bats-core
  URL=https://github.com/bats-core/bats-core.git
  BRANCH=master
  ;;
  2)
  DIR=external/bats-support
  URL=https://github.com/bats-core/bats-support.git
  BRANCH=master
  ;;
  3)
  DIR=external/bats-assert
  URL=https://github.com/bats-core/bats-assert.git
  BRANCH=master
  ;;
  4)
  DIR=external/bats-file
  URL=https://github.com/bats-core/bats-file.git
  BRANCH=master
  ;;
  5)
  DIR=external/bats-mock
  URL=https://github.com/buildkite-plugins/bats-mock.git
  BRANCH=master
  ;;
  6)
  DIR=external/googletest
  URL=https://github.com/google/googletest.git
  BRANCH=v1.10.x
  ;;
  7)
  DIR=external/pybind11
  URL=https://github.com/pybind/pybind11.git
  BRANCH=v2.9
  ;;
  8)
  DIR=external/petsc
  URL=https://gitlab.com/petsc/petsc.git
  BRANCH=release
  ;;
  9)
  DIR=external/gmsh
  URL=https://gitlab.onelab.info/gmsh/gmsh.git
  BRANCH=master
  ;;
  10)
  DIR=external/freetype
  URL=https://gitlab.gnome.org/GNOME/libxml2.git
  BRANCH=master
  ;;
  11)
  DIR=external/fltk
  URL=https://github.com/fltk/fltk.git
  BRANCH=branch-1.3
  ;;
  12)
  DIR=external/xml2
  URL=https://github.com/fltk/fltk.git
  BRANCH=master
  ;;
  13)
  DIR=external/povray
  URL=https://github.com/POV-Ray/povray.git
  BRANCH=latest-stable
  ;;
  14)
  DIR=external/neper
  URL=https://github.com/neperfepx/neper.git
  BRANCH=main
  ;;
  15)
  DIR=external/sdl
  URL=https://github.com/libsdl-org/SDL.git
  BRANCH=SDL2
  ;;
  16)
  DIR=external/openexr
  URL=https://github.com/AcademySoftwareFoundation/openexr
  BRANCH=release
  ;;
#  6)
#  DIR=external/cgns
#  URL=https://github.com/CGNS/CGNS.git
#  BRANCH=master
#  ;;
  esac
  if [ "$DIR" != "" ]; then
    git submodule add --force -b "$BRANCH" "$URL" "$DIR"
  fi
done
echo 'update and init all submodules and their submodules recursively...'
git submodule update --init --recursive 
#
