#!/bin/bash


if [ ! -z "$1" ]; then
  OUTDIR="build/"${1/src/}
  mkdir -p "$OUTDIR"
  `python3 -m unittest discover -s "$1" -p '*_test.py' 1> "$OUTDIR/test.out" 2> "$OUTDIR/test.err" `
else
  >&2 echo "Please provide a directory."
fi
