#!/bin/bash
#
#
if [ 0 == 1 ]; then
if [ -z "OMP_NUM_THREADS" ]; then
  N=`echo "$@" | grep -ioP '(?<=PE\=)[0-9]+'`
  if [ ! -z "$N" ]; then
    export OMP_NUM_THREADS=$N
  fi
fi
fi
export OMP_PROC_BIND=close
export OMP_PLACES=cores
$@
exit $?
#
